### ISSUE TITLE
i cant find the missions 

### ISSUE THREAD

**Issue by Omar-Tahsin** [AcidCaos/raisetheempires#14]
i cant find the missions in the left of the padge
![Screenshot_2021-01-15 Empires Allies on Facebook Facebook](https://user-images.githubusercontent.com/75571116/104725102-4575cd80-573a-11eb-86f6-7661629a59d8.png)

**Comment by AcidCaos** [comment]
You have to deactivate the gameRevision_107829_settings mod.

How?
Go to your game installation folder, then go to /mods and open mods.conf file. Inside there's this line:

gameRevision_107829_settings = true

Change it from true to false:

gameRevision_107829_settings = false

You have to restart the program.

**Comment by Omar-Tahsin** [comment]
thank you its working
