### ISSUE TITLE
HELP PLZ!

### ISSUE THREAD

**Issue by ipman1001** [AcidCaos/raisetheempires#21]

**Comment by AcidCaos** [comment]
Find 'RaiseTheEmpires.ini' on your installation folder and fix the 'MyGamesPath' value from [InstallFolders]. It seems that there are some '?' characters, which are invalid.

**Comment by ipman1001** [comment]
bro i love thnx very much really but i have some more question why i am already 85 level ?

**Comment by ipman1001** [comment]
really thnxxxxx bro <3

**Comment by ipman1001** [comment]
never mind i get it i start new player ty bro love y
